repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Import Statements
        files: .py$
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        name: Paint It Black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Lint with Flake8
        files: .py$
        args:
          - --max-line-length=89
