[tool.poetry]
name = "hello_world"
version = "0.1.0"
description = "A template package"
authors = ["endlesstrax <ricky@whitelionmedia.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
isort = "^5.9.3"
pre-commit = "^2.15.0"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
