name: Lint and Format

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install ruff
        python -m pip install black
    
    - name: Run Ruff
      run: ruff .

    - name: Run Black
      run: black .