name: Run Tests

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ['3.10']
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install poetry
        poetry env use ${{ matrix.python-version }} 
        poetry install
    
    - name: Run pytest
      run: poetry run pytest --cov